In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('/Users/retnolintang/Downloads/Taxi Trip Duration Predictions/Data/Cleaned NYC Taxi Trip Data (2025 Sample).csv')

df.head().T

,0,1,2,3,4
VendorID,2,1,1,2,2
tpep_pickup_datetime,2025-01-18 20:53:30,2025-01-25 11:12:51,2025-01-21 15:09:31,2025-01-11 22:25:45,2025-01-04 23:37:07
tpep_dropoff_datetime,2025-01-18 21:00:47,2025-01-25 11:17:57,2025-01-21 15:19:02,2025-01-11 22:34:22,2025-01-04 23:45:58
passenger_count,1,1,1,2,1
trip_distance,0.97,0.6,0.8,1.93,4.44
RatecodeID,1,1,1,1,1
store_and_fwd_flag,N,N,N,N,N
PULocationID,238,50,236,231,137
DOLocationID,166,48,237,68,88
payment_type,1,2,1,1,0
fare_amount,8.6,5.8,9.3,10.7,26.3
extra,1.0,3.25,2.5,1.0,0.0
mta_tax,0.5,0.5,0.5,0.5,0.5
tip_amount,2.22,0.0,3.35,3.92,4.82
tolls_amount,0.0,0.0,0.0,0.0,0.0
improvement_surcharge,1.0,1.0,1.0,1.0,1.0
total_amount,13.32,10.55,16.65,20.37,35.12
congestion_surcharge,0.0,2.5,2.5,2.5,0.0
Airport_fee,0.0,0.0,0.0,0.0,NaN
cbd_congestion_fee,0.0,0.75,0.0,0.75,0.0
duration_min,7.283333,5.1,9.516667,8.616667,8.85
speed_mph,7.990847,7.058824,5.043783,13.439072,30.101695
pickup_hour,20,11,15,22,23
day_of_week,Saturday,Saturday,Tuesday,Saturday,Saturday
is_weekend,True,True,False,True,True

In [2]:
df.shape

(3946698, 25)

In [3]:
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee', 'duration_min', 'speed_mph', 'pickup_hour',
       'day_of_week', 'is_weekend'],
      dtype='str')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3946698 entries, 0 to 3946697
Data columns (total 25 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   str
 2   tpep_dropoff_datetime  str
 3   passenger_count        int64
 4   trip_distance          float64
 5   RatecodeID             int64
 6   store_and_fwd_flag     str
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
 20  duration_min           float64
 21  speed_mph              float64
 22  pickup_hour            int64
 23  day_of_week            str
 24  is_weekend             bool
dtypes: bool(1), float64(13), int64(7), str(4)
memory usage: 900.3 MB

In [5]:
df.describe()

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration_min,speed_mph,pickup_hour
count,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.189311e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06
mean,1.787345e+00,1.233373e+00,3.441244e+00,2.710091e+00,1.620718e+02,1.611536e+02,9.466660e-01,1.936859e+01,1.307855e+00,4.963577e-01,3.028975e+00,5.057680e-01,9.830288e-01,2.813628e+01,1.861057e+00,1.493874e-01,5.504911e-01,1.697423e+01,1.102928e+01,1.420994e+01
std,4.194354e-01,6.595587e-01,4.121952e+00,1.264134e+01,6.562439e+01,7.000420e+01,6.359776e-01,1.576509e+01,1.842253e+00,4.729320e-02,3.787247e+00,1.986163e+00,1.288213e-01,1.988695e+01,1.090462e+00,4.889902e-01,3.314068e-01,1.339776e+01,6.144650e+00,5.989917e+00
min,1.000000e+00,0.000000e+00,1.100000e-01,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e-02,-1.739000e+01,-7.810000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.010000e+00,0.000000e+00,0.000000e+00,-7.500000e-01,1.000000e+00,1.000000e+00,0.000000e+00
25%,2.000000e+00,1.000000e+00,1.100000e+00,1.000000e+00,1.220000e+02,1.070000e+02,1.000000e+00,9.300000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.656000e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.266667e+00,7.082405e+00,1.000000e+01
50%,2.000000e+00,1.000000e+00,1.900000e+00,1.000000e+00,1.610000e+02,1.620000e+02,1.000000e+00,1.420000e+01,0.000000e+00,5.000000e-01,2.450000e+00,0.000000e+00,1.000000e+00,2.186000e+01,2.500000e+00,0.000000e+00,7.500000e-01,1.338333e+01,9.486166e+00,1.500000e+01
75%,2.000000e+00,1.000000e+00,3.700000e+00,1.000000e+00,2.330000e+02,2.330000e+02,1.000000e+00,2.260000e+01,2.500000e+00,5.000000e-01,4.070000e+00,0.000000e+00,1.000000e+00,3.085000e+01,2.500000e+00,0.000000e+00,7.500000e-01,2.116667e+01,1.303040e+01,1.900000e+01
max,6.000000e+00,9.000000e+00,9.906000e+01,9.900000e+01,2.630000e+02,2.630000e+02,4.000000e+00,1.334020e+03,1.500000e+01,2.214000e+01,5.500000e+02,1.158700e+02,1.000000e+00,1.345710e+03,2.500000e+00,1.750000e+00,1.500000e+00,1.799667e+02,8.000000e+01,2.300000e+01

In [6]:
df.isnull().sum()

VendorID                      0
tpep_pickup_datetime          0
tpep_dropoff_datetime         0
passenger_count               0
trip_distance                 0
RatecodeID                    0
store_and_fwd_flag            0
PULocationID                  0
DOLocationID                  0
payment_type                  0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
improvement_surcharge         0
total_amount                  0
congestion_surcharge          0
Airport_fee              757387
cbd_congestion_fee            0
duration_min                  0
speed_mph                     0
pickup_hour                   0
day_of_week                   0
is_weekend                    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

# Data Understanding

## Dataset Information

Dataset yang digunakan adalah NYC Taxi Trip Data 2025 Sample yang berisi informasi historis perjalanan taksi di New York City.

Tujuan analisis adalah membangun model Machine Learning untuk memprediksi durasi perjalanan (trip duration) guna membantu perusahaan transportasi meningkatkan efisiensi operasional.

## Business Problem

Perusahaan transportasi mengalami kesulitan memperkirakan durasi perjalanan secara akurat sehingga mengganggu perencanaan operasional.

## Machine Learning Problem

Membangun model regresi untuk memprediksi durasi perjalanan berdasarkan karakteristik perjalanan pelanggan.

## Dataset Summary

| Informasi | Hasil |
|-----------|-------|
| Jumlah data | 3.946.698 baris |
| Jumlah fitur | 25 kolom |
| Missing value | 757.387 data |
| Kolom yang memiliki missing value | Airport_fee |
| Duplicate data | 0 |
| Target variabel | duration_min |
| Jenis permasalahan | Regression |

## Temuan Awal

1. Dataset memiliki **3.946.698 data perjalanan** sehingga cukup besar untuk membangun model prediksi yang stabil.

2. Dataset memiliki **25 fitur** yang terdiri dari:

- 13 kolom numerik (`float64`)
- 7 kolom numerik (`int64`)
- 4 kolom kategorikal (`object/string`)
- 1 kolom boolean

3. Tidak ditemukan data duplikat.

4. Terdapat missing value pada kolom `Airport_fee` sebanyak **757.387 data**.

5. Target prediksi yang akan digunakan adalah `duration_min`.

6. Proyek ini termasuk ke dalam **Supervised Machine Learning - Regression Problem**.