In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('/Users/retnolintang/Downloads/Taxi Trip Duration Predictions/Data/Cleaned NYC Taxi Trip Data (2025 Sample).csv')

df.head().T

,0,1,2,3,4
VendorID,2,1,1,2,2
tpep_pickup_datetime,2025-01-18 20:53:30,2025-01-25 11:12:51,2025-01-21 15:09:31,2025-01-11 22:25:45,2025-01-04 23:37:07
tpep_dropoff_datetime,2025-01-18 21:00:47,2025-01-25 11:17:57,2025-01-21 15:19:02,2025-01-11 22:34:22,2025-01-04 23:45:58
passenger_count,1,1,1,2,1
trip_distance,0.97,0.6,0.8,1.93,4.44
RatecodeID,1,1,1,1,1
store_and_fwd_flag,N,N,N,N,N
PULocationID,238,50,236,231,137
DOLocationID,166,48,237,68,88
payment_type,1,2,1,1,0
fare_amount,8.6,5.8,9.3,10.7,26.3
extra,1.0,3.25,2.5,1.0,0.0
mta_tax,0.5,0.5,0.5,0.5,0.5
tip_amount,2.22,0.0,3.35,3.92,4.82
tolls_amount,0.0,0.0,0.0,0.0,0.0
improvement_surcharge,1.0,1.0,1.0,1.0,1.0
total_amount,13.32,10.55,16.65,20.37,35.12
congestion_surcharge,0.0,2.5,2.5,2.5,0.0
Airport_fee,0.0,0.0,0.0,0.0,NaN
cbd_congestion_fee,0.0,0.75,0.0,0.75,0.0
duration_min,7.283333,5.1,9.516667,8.616667,8.85
speed_mph,7.990847,7.058824,5.043783,13.439072,30.101695
pickup_hour,20,11,15,22,23
day_of_week,Saturday,Saturday,Tuesday,Saturday,Saturday
is_weekend,True,True,False,True,True

In [3]:
# Drop kolom yang tidak dipakai

df = df.drop(
    columns=[
        'tpep_pickup_datetime',
        'tpep_dropoff_datetime'
    ],
    errors='ignore'
)

df.head().T

                              0         1         2          3          4
VendorID                      2         1         1          2          2
passenger_count               1         1         1          2          1
trip_distance              0.97       0.6       0.8       1.93       4.44
RatecodeID                    1         1         1          1          1
store_and_fwd_flag            N         N         N          N          N
PULocationID                238        50       236        231        137
DOLocationID                166        48       237         68         88
payment_type                  1         2         1          1          0
fare_amount                 8.6       5.8       9.3       10.7       26.3
extra                       1.0      3.25       2.5        1.0        0.0
mta_tax                     0.5       0.5       0.5        0.5        0.5
tip_amount                 2.22       0.0      3.35       3.92       4.82
tolls_amount                0.0       0.0       0.0        0.0        0.0
improvement_surcharge       1.0       1.0       1.0        1.0        1.0
total_amount              13.32     10.55     16.65      20.37      35.12
congestion_surcharge        0.0       2.5       2.5        2.5        0.0
Airport_fee                 0.0       0.0       0.0        0.0        NaN
cbd_congestion_fee          0.0      0.75       0.0       0.75        0.0
duration_min           7.283333       5.1  9.516667   8.616667       8.85
speed_mph              7.990847  7.058824  5.043783  13.439072  30.101695
pickup_hour                  20        11        15         22         23
day_of_week            Saturday  Saturday   Tuesday   Saturday   Saturday
is_weekend                 True      True     False       True       True

In [4]:
#Handle missing value
df['Airport_fee'] = df['Airport_fee'].fillna(0)
df.isnull().sum()

VendorID                 0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
Airport_fee              0
cbd_congestion_fee       0
duration_min             0
speed_mph                0
pickup_hour              0
day_of_week              0
is_weekend               0
dtype: int64

In [5]:
#Encoding data kategorikal
categorical_cols = [
    'store_and_fwd_flag',
    'day_of_week'
]

le = LabelEncoder()

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])
df['is_weekend'] = df['is_weekend'].astype(int)

df.head().T

,0,1,2,3,4
VendorID,2.000000,1.000000,1.000000,2.000000,2.000000
passenger_count,1.000000,1.000000,1.000000,2.000000,1.000000
trip_distance,0.970000,0.600000,0.800000,1.930000,4.440000
RatecodeID,1.000000,1.000000,1.000000,1.000000,1.000000
store_and_fwd_flag,0.000000,0.000000,0.000000,0.000000,0.000000
PULocationID,238.000000,50.000000,236.000000,231.000000,137.000000
DOLocationID,166.000000,48.000000,237.000000,68.000000,88.000000
payment_type,1.000000,2.000000,1.000000,1.000000,0.000000
fare_amount,8.600000,5.800000,9.300000,10.700000,26.300000
extra,1.000000,3.250000,2.500000,1.000000,0.000000
mta_tax,0.500000,0.500000,0.500000,0.500000,0.500000
tip_amount,2.220000,0.000000,3.350000,3.920000,4.820000
tolls_amount,0.000000,0.000000,0.000000,0.000000,0.000000
improvement_surcharge,1.000000,1.000000,1.000000,1.000000,1.000000
total_amount,13.320000,10.550000,16.650000,20.370000,35.120000
congestion_surcharge,0.000000,2.500000,2.500000,2.500000,0.000000
Airport_fee,0.000000,0.000000,0.000000,0.000000,0.000000
cbd_congestion_fee,0.000000,0.750000,0.000000,0.750000,0.000000
duration_min,7.283333,5.100000,9.516667,8.616667,8.850000
speed_mph,7.990847,7.058824,5.043783,13.439072,30.101695
pickup_hour,20.000000,11.000000,15.000000,22.000000,23.000000
day_of_week,2.000000,2.000000,5.000000,2.000000,2.000000
is_weekend,1.000000,1.000000,0.000000,1.000000,1.000000

In [6]:
# Hapus kolom yang menyebabkan data leakage
leakage_cols = [
    'payment_type',
    'speed_mph',
    'fare_amount',
    'tip_amount',
    'tolls_amount',
    'extra',
    'total_amount',
    'congestion_surcharge',
    'Airport_fee',
    'mta_tax',
    'improvement_surcharge',
    'store_and_fwd_flag',
    'cbd_congestion_fee'
]

# Hapus kolom yang memang masih ada
df = df.drop(
    columns=[col for col in leakage_cols if col in df.columns]
)

# Pisahkan fitur dan target
X = df.drop('duration_min', axis=1)

y = df['duration_min']

In [7]:
#Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(3157358, 9)
(789340, 9)

## Insight

Dataset berhasil dipisahkan menjadi data latih dan data uji dengan rasio 80:20.

- Data latih (X_train): 3.157.358 baris dan 9 fitur
- Data uji (X_test): 789.340 baris dan 9 fitur

Data ini akan digunakan untuk membangun dan mengevaluasi model prediksi durasi perjalanan.

In [8]:
# Simpan dataset hasil preprocessing

X_train.to_csv('../Data/X_train.csv', index=False)

X_test.to_csv('../Data/X_test.csv', index=False)

y_train.to_csv('../Data/y_train.csv', index=False)

y_test.to_csv('../Data/y_test.csv', index=False)

print('File berhasil disimpan.')

File berhasil disimpan.